<style>
    body {background: #f9fee8;margin: 0; padding: 20px; text-align:center; font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#666666;}
    .error_page { padding: 50px; margin: auto;}
    .error_page h1 {margin: 20px 0 0;}
    .error_page p {margin: 10px 0; padding: 0;}
    a {color: #748151; text-decoration:none;}
    a:hover {color: #9caa6d; text-decoration:underline;}
    img{max-width:100%}
</style>

<div class="error_page">
    <h1>Omlouváme se... </h1>
    <p>Stránku, kterou hledáte, nelze najít</p>
    <p><a href="">Vrátit se na domovskou stránku.</a></p>
</div>
