<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/" />
    <meta charset="UTF-8" />
    <title><?= $title ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $keyWords ?>" />
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
    <link rel="shortcut icon" href="favicon.ico">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <?php $this->controller->show(); ?>
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.tablesorter.min.js"></script>
<script src="js/main.js"></script>
</html>
